# Generated by Django 5.0.4 on 2024-06-05 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_name_pokoj_nazwa_pokoj_opis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uprawnieniauzytkownika',
            name='device',
        ),
        migrations.AddField(
            model_name='uprawnieniauzytkownika',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.pokoj'),
        ),
    ]
